### ISSUE TITLE
Panic on startup (sometimes?)

### ISSUE THREAD

**Issue by joshk0** [frodenas/stackdriver_exporter#4]
```

time="2017-07-13T14:16:56Z" level=info msg="Starting stackdriver_exporter (version=0.1.0, branch=master, revision=6d10015859810acccfdfb490c582c7a7c71e8e6d)" source="stackdriver_exporter.go:120"
--
time="2017-07-13T14:16:56Z" level=info msg="Build context (go=go1.8.1, user=root@cc89fcb97b70, date=20170603-18:39:47)" source="stackdriver_exporter.go:121"
time="2017-07-13T14:16:56Z" level=info msg="Listening on :9255" source="stackdriver_exporter.go:147"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x76755a]
 
goroutine 41182 [running]:
github.com/frodenas/stackdriver_exporter/collectors.(*MonitoringCollector).reportTimeSeriesMetrics(0xc4201132c0, 0x0, 0xc4204a89c0, 0xc4201a0b40, 0x0, 0xa0a1c0)
/go/src/github.com/frodenas/stackdriver_exporter/collectors/monitoring_collector.go:233 +0x3a
github.com/frodenas/stackdriver_exporter/collectors.(*MonitoringCollector).reportMonitoringMetrics.func1.1(0xc420373340, 0xc4201132c0, 0xed0f9901a, 0xc425cf1736, 0x0, 0xed0f99146, 0xc425cf17b4, 0x0, 0xc42007e3c0, 0xc4204a89c0, ...)
/go/src/github.com/frodenas/stackdriver_exporter/collectors/monitoring_collector.go:170 +0x5e6
created by github.com/frodenas/stackdriver_exporter/collectors.(*MonitoringCollector).reportMonitoringMetrics.func1
/go/src/github.com/frodenas/stackdriver_exporter/collectors/monitoring_collector.go:178 +0x28b


```

**Comment by frodenas** [comment]
Thanks for reporting it. This should be fixed at [v0.1.1](https://github.com/frodenas/stackdriver_exporter/releases/tag/v0.1.1).
